#!/usr/bin/env python3
"""build-cases.py: regenerate every case input and assemble goldens/cases.tsv.

goldens/cases.tsv = header + cases/hand-cases.tsv + cases/fixture-cases.tsv
(the manifest is generated; the GOLDENS beside it are captured, never generated).
usage: python3 cases/build-cases.py [--check]     exit 0 OK/WRITTEN, 1 DRIFT
"""
import json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
HEADER = """# Toon conformance cases: name<TAB>argv (JSON string array)<TAB>stdin file or -<TAB>class<TAB>note
# GENERATED by cases/build-cases.py (cases/gen-hand-cases.py + cases/gen-fixture-cases.py). Do not edit:
# change a generator, run `python3 cases/build-cases.py`, then re-capture with --repin "<reason>".
# Capture:  scripts/golden-capture.sh goldens/cases.tsv goldens -- ./oracle/toon
# Floor:    scripts/floor.sh goldens/cases.tsv goldens --repeat 3 -- ./oracle/toon
# Check:    scripts/lanes.sh goldens/cases.tsv goldens port/main.bend
"""


def _read_bytes(path):
    """The bytes of a file; the handle is closed before returning."""
    with open(path, "rb") as fh:
        return fh.read()


def main():
    check = "--check" in sys.argv[1:]
    extra = ["--check"] if check else []
    rc = 0
    for gen in ("gen-hand-cases.py", "gen-fixture-cases.py"):
        rc |= subprocess.run([sys.executable, os.path.join(HERE, gen), *extra]).returncode
    body = ""
    for part in ("hand-cases.tsv", "fixture-cases.tsv"):
        with open(os.path.join(HERE, part), encoding="utf-8") as fh:
            body += "".join(l for l in fh if not l.startswith("#"))
    text = HEADER + body
    out = os.path.join(ROOT, "goldens", "cases.tsv")
    n = sum(1 for l in body.splitlines() if l.strip())
    if check:
        same = os.path.exists(out) and _read_bytes(out).decode("utf-8") == text
        print(json.dumps({"cases": n, "verdict": "OK" if same and rc == 0 else "DRIFT"}))
        return 0 if same and rc == 0 else 1
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(json.dumps({"cases": n, "verdict": "WRITTEN"}))
    return rc


if __name__ == "__main__":
    sys.exit(main())
