#!/usr/bin/env python3
"""gen-fixture-cases.py: turn the vendored TOON spec fixtures into conformance cases.

Reads   cases/fixtures/spec/{encode,decode}/*.json   (vendored from toon-format/spec,
        the copy toon_rust ships under tests/fixtures/spec at the pinned commit)
Writes  cases/inputs/fx/<case>.json|.toon             (the bytes fed to stdin)
        cases/fixture-cases.tsv                        (rows for goldens/cases.tsv)

Only the fixtures' *inputs* and *options* are used. Their "expected" fields come
from the upstream TypeScript reference and are NOT goldens here: the goldens are
captured by running the pinned toon_rust binary (scripts/golden-capture.sh).

Number literals in encode inputs are written with their original text (1e6 stays
1e6, -0 stays -0): the literal is part of the behavior under test.

Deterministic: same fixtures in, same files out. Case names are
fx_<enc|dec>_<file>_<NN> with NN the 1-based index inside the fixture file, so a
name is stable for as long as the vendored fixture file is unchanged.
usage: python3 cases/gen-fixture-cases.py [--check]
"""
import json, os, sys, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FX = os.path.join(ROOT, "cases", "fixtures", "spec")
OUT_INPUTS = os.path.join(ROOT, "cases", "inputs", "fx")
OUT_TSV = os.path.join(ROOT, "cases", "fixture-cases.tsv")


class Raw(str):
    """A JSON number literal kept as its source text."""


def dump(v):
    if isinstance(v, Raw):
        return str(v)
    if v is None:
        return "null"
    if v is True:
        return "true"
    if v is False:
        return "false"
    if isinstance(v, str):
        try:
            v.encode("utf-8")
            return json.dumps(v, ensure_ascii=False)
        except UnicodeEncodeError:  # lone surrogate: keep it as an escape
            return json.dumps(v, ensure_ascii=True)
    if isinstance(v, list):
        return "[" + ",".join(dump(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ",".join(dump(k) + ":" + dump(x) for k, x in v.items()) + "}"
    raise TypeError(type(v))


def args_for(kind, options):
    args = ["--encode"] if kind == "encode" else ["--decode"]
    o = dict(options or {})
    if "delimiter" in o:
        args += ["--delimiter", str(o.pop("delimiter"))]
    if "indent" in o:
        args += ["--indent", str(o.pop("indent"))]
    if "keyFolding" in o:
        args += ["--key-folding", str(o.pop("keyFolding"))]
    if "flattenDepth" in o:
        args += ["--flatten-depth", str(o.pop("flattenDepth"))]
    if "expandPaths" in o:
        args += ["--expand-paths", str(o.pop("expandPaths"))]
    if "strict" in o:
        if o.pop("strict") is False:
            args += ["--no-strict"]
    if o:
        raise SystemExit(f"unmapped fixture options: {o}")
    return args


def _read_bytes(path):
    """The bytes of a file; the handle is closed before returning."""
    with open(path, "rb") as fh:
        return fh.read()


def main():
    check = "--check" in sys.argv[1:]
    os.makedirs(OUT_INPUTS, exist_ok=True)
    rows, files = [], {}
    for kind, short in (("encode", "enc"), ("decode", "dec")):
        for path in sorted(glob.glob(os.path.join(FX, kind, "*.json"))):
            stem = os.path.splitext(os.path.basename(path))[0].replace("-", "_")
            with open(path, encoding="utf-8") as fh:
                doc = json.loads(fh.read(), parse_int=Raw, parse_float=Raw)
            for i, t in enumerate(doc["tests"], 1):
                name = f"fx_{short}_{stem}_{i:02d}"
                if kind == "encode":
                    rel = f"cases/inputs/fx/{name}.json"
                    data = (dump(t["input"]) + "\n").encode("utf-8")
                else:
                    rel = f"cases/inputs/fx/{name}.toon"
                    data = t["input"].encode("utf-8")  # exact document bytes, no newline added
                files[rel] = data
                cls = f"fixture-{kind}" + ("-error" if t.get("shouldError") else "")
                rows.append((name, json.dumps(args_for(kind, t.get("options"))), rel, cls,
                             f"{os.path.basename(path)}#{i} {t['name']}"))
    tsv = "# generated by cases/gen-fixture-cases.py from cases/fixtures/spec; do not edit\n"
    tsv += "".join("\t".join(r) + "\n" for r in rows)
    drift = []
    for rel, data in files.items():
        p = os.path.join(ROOT, rel)
        if check:
            if not os.path.exists(p) or _read_bytes(p) != data:
                drift.append(rel)
        else:
            with open(p, "wb") as fh:
                fh.write(data)
    if check:
        if not os.path.exists(OUT_TSV) or _read_bytes(OUT_TSV).decode("utf-8") != tsv:
            drift.append("cases/fixture-cases.tsv")
        print(json.dumps({"cases": len(rows), "drift": drift, "verdict": "OK" if not drift else "DRIFT"}))
        return 1 if drift else 0
    with open(OUT_TSV, "w", encoding="utf-8") as fh:
        fh.write(tsv)
    print(json.dumps({"cases": len(rows), "inputs": len(files), "verdict": "WRITTEN"}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
